# Ass 1

### Ques1

In [ ]:
import numpy as np

In [ ]:
#a reverse array
arr = np.array([1, 2, 3, 4, 5])
print(np.flip(arr))
print(arr[::-1])

#b flatten the array
arr1 = np.array([[1,2,3], [2,4,5], [1,2,3]])
print(arr1.flatten())
print(arr1.reshape(3,3))

#c compare
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[1,2],[3,4]])
print(np.array_equal(a1,a2))

#d most freq value and their indices
x = np.array([1,2,3,4,5,1,2,1,1,1])
values, counts = np.unique(x, return_counts=True)
most_freq_val = values[np.argmax(counts)]
indices = np.where(x == most_freq_val)[0]
print("For x:")
print("Most frequent value:", most_freq_val)
print("Indices:", indices)
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
values, counts = np.unique(y, return_counts=True)
most_freq_val = values[np.argmax(counts)]
indices = np.where(y == most_freq_val)[0]
print("\nFor y:")
print("Most frequent value:", most_freq_val)
print("Indices:", indices)

#e find sums

gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
total_sum = gfg.sum()
row_sum = gfg.sum(axis=1)
col_sum = gfg.sum(axis=0)

print("\nFor gfg matrix:")
print("Sum of all elements:", total_sum)
print("Sum row-wise:", row_sum)
print("Sum column-wise:", col_sum)

#f matrix
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
diag_sum = np.trace(n_array)
eig_vals, eig_vecs = np.linalg.eig(n_array)
inv_matrix = np.linalg.inv(n_array)
det_matrix = np.linalg.det(n_array)

print("\nFor n_array matrix:")
print("Sum of diagonal elements:", diag_sum)
print("Eigen values:", eig_vals)
print("Eigen vectors:\n", eig_vecs)
print("Inverse of matrix:\n", inv_matrix)
print("Determinant of matrix:", det_matrix)

#g Multiply matrices and co variance
# i.
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
product1 = np.matmul(p1, q1)
covariance1 = np.cov(p1.flatten(), q1.flatten())
# ii.
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
product2 = np.matmul(p2, q2)
covariance2 = np.cov(p2.flatten(), q2.flatten())

print("\nMatrix multiplication and covariance:")
print("i. Product:\n", product1)
print("i. Covariance:\n", covariance1)
print("\nii. Product:\n", product2)
print("ii. Covariance:\n", covariance2)

#h products

x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

# Inner product: sum of products of elements at corresponding positions
inner_product = np.inner(x, y)

# Outer product: for 1D arrays, but here we'll flatten first
outer_product = np.outer(x.flatten(), y.flatten())

# Cartesian product: all pairs of rows from x and y combined
cartesian_product = np.array([(a, b) for a in x for b in y])

print("\nFor matrices x and y:")
print("Inner product:\n", inner_product)
print("Outer product:\n", outer_product)
print("Cartesian product shape:", cartesian_product.shape)
print("Cartesian product (first few pairs):\n", cartesian_product[:4])




[5 4 3 2 1]
[5 4 3 2 1]
[1 2 3 2 4 5 1 2 3]
[[1 2 3]
 [2 4 5]
 [1 2 3]]
True
For x:
Most frequent value: 1
Indices: [0 5 7 8 9]

For y:
Most frequent value: 1
Indices: [0 1 2]

For gfg matrix:
Sum of all elements: 45
Sum row-wise: [[14]
 [16]
 [15]]
Sum column-wise: [[20  9 16]]

For n_array matrix:
Sum of diagonal elements: 176
Eigen values: [98.16835147 28.097044   49.73460452]
Eigen vectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of matrix: 137180.0000000001

Matrix multiplication and covariance:
i. Product:
 [[16 19]
 [26 31]]
i. Covariance:
 [[0.66666667 1.        ]
 [1.         1.66666667]]

ii. Product:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
ii. Covariance:
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]

For matrices x and y:
Inner product:
 [[17 52

##Ques 2

In [14]:
#a
array = np.array([[1, -2, 3], [-4, 5, -6]])

# i. Element-wise absolute value
abs_array = np.abs(array)

# ii. Percentiles (25th, 50th, 75th)
# Flattened array percentiles
percentiles_flat = np.percentile(array, [25, 50, 75])

# Percentiles for each column
percentiles_col = np.percentile(array, [25, 50, 75], axis=0)

# Percentiles for each row
percentiles_row = np.percentile(array, [25, 50, 75], axis=1)

# iii. Mean, Median, Standard Deviation
# Flattened
mean_flat = np.mean(array)
median_flat = np.median(array)
std_flat = np.std(array)

# For each column
mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
std_col = np.std(array, axis=0)

# For each row
mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)

print("Element-wise absolute value:\n", abs_array)
print("\nPercentiles (25th, 50th, 75th) of flattened array:", percentiles_flat)
print("Percentiles for each column:\n", percentiles_col)
print("Percentiles for each row:\n", percentiles_row)

print("\nMean, Median, Std of flattened array:", mean_flat, median_flat, std_flat)
print("Mean for each column:", mean_col)
print("Median for each column:", median_col)
print("Std for each column:", std_col)
print("Mean for each row:", mean_row)
print("Median for each row:", median_row)
print("Std for each row:", std_row)


Element-wise absolute value:
 [[1 2 3]
 [4 5 6]]

Percentiles (25th, 50th, 75th) of flattened array: [-3.5 -0.5  2.5]
Percentiles for each column:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles for each row:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]

Mean, Median, Std of flattened array: -0.5 -0.5 3.8622100754188224
Mean for each column: [-1.5  1.5 -1.5]
Median for each column: [-1.5  1.5 -1.5]
Std for each column: [2.5 3.5 4.5]
Mean for each row: [ 0.66666667 -1.66666667]
Median for each row: [ 1. -4.]
Std for each row: [2.05480467 4.78423336]


In [13]:
#b
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

floor_values = np.floor(a)
ceil_values = np.ceil(a)
trunc_values = np.trunc(a)
round_values = np.round(a)

print("\nFloor values:", floor_values)
print("Ceiling values:", ceil_values)
print("Truncated values:", trunc_values)
print("Rounded values:", round_values)


Floor values: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded values: [-2. -2. -0.  0.  2.  2.  3.]


##Ques3

In [12]:
#a
array = np.array([10, 52, 62, 16, 16, 54, 453])

# i. Sorted array
sorted_array = np.sort(array)

# ii. Indices of sorted array
sorted_indices = np.argsort(array)

# iii. 4 smallest elements
smallest_4 = np.partition(array, 3)[:4]

# iv. 5 largest elements
largest_5 = np.partition(array, -5)[-5:]
largest_5_sorted = np.sort(largest_5)  # Optional: sorted largest 5

print("Sorted array:", sorted_array)
print("Indices of sorted array:", sorted_indices)
print("4 smallest elements:", smallest_4)
print("5 largest elements:", largest_5_sorted)


Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]


In [11]:
#b
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

# i. Integer elements only (checking if float values are whole numbers)
integer_elements = array[array == np.floor(array)]

# ii. Float elements only (non-integers)
float_elements = array[array != np.floor(array)]

print("\nInteger elements only:", integer_elements)
print("Float elements only:", float_elements)


Integer elements only: [1. 2. 3. 2.]
Float elements only: [1.2 2.2]


##Ques 4

In [9]:
#a Function img_to_array(path):
from PIL import Image
import numpy as np

def img_to_array(path):
    # Open image
    img = Image.open(path)

    # Convert to numpy array
    arr = np.array(img)

    # Convert to grayscale if it's an RGB image with R=G=B
    if len(arr.shape) == 3 and arr.shape[2] == 3:
        if (arr[:, :, 0] == arr[:, :, 1]).all() and (arr[:, :, 0] == arr[:, :, 2]).all():
            arr = arr[:, :, 0] # Convert to 2D grayscale array

    # Check if image is grayscale or RGB
    if len(arr.shape) == 2 or (len(arr.shape) == 3 and arr.shape[2] == 1):
        # Grayscale image
        filename = "grayscale_image.txt"
        np.savetxt(filename, arr, fmt='%d')
        print(f"Grayscale image saved as {filename}")
    elif len(arr.shape) == 3 and arr.shape[2] == 3:
        # RGB image
        filename = "rgb_image.txt"
        # Save as flattened array with shape info
        # Save shape in first line, then flatten array values
        with open(filename, 'w') as f:
            # Write shape
            f.write(f"{arr.shape[0]} {arr.shape[1]} {arr.shape[2]}\n")
            # Write flattened pixel data
            flat_arr = arr.reshape(-1, 3)
            np.savetxt(f, flat_arr, fmt='%d')
        print(f"RGB image saved as {filename}")
    else:
        print("Unsupported image format")

# Example usage:
img_to_array('/content/greypar.png')
img_to_array('/content/random.jpg')

Grayscale image saved as grayscale_image.txt
RGB image saved as rgb_image.txt


In [10]:
#b  Load the saved file into Jupyter Notebook:
def load_image_array(filename):
    try:
        with open(filename, 'r') as f:
            first_line = f.readline().strip()
            dims = first_line.split()

            if len(dims) == 3:
                # RGB image
                rows, cols, channels = map(int, dims)
                data = np.loadtxt(f, dtype=int)
                arr = data.reshape((rows, cols, channels))
                print("Loaded RGB image array with shape:", arr.shape)
                return arr
            else:
                # Grayscale image
                # Reset file pointer to start
                f.seek(0)
                arr = np.loadtxt(f, dtype=int)
                print("Loaded Grayscale image array with shape:", arr.shape)
                return arr
    except FileNotFoundError:
        print(f"Error: The file '{filename}' was not found.")
        return None

# Example usage:
gray_arr = load_image_array('grayscale_image.txt')
rgb_arr = load_image_array('rgb_image.txt')

Loaded Grayscale image array with shape: (512, 768)
Loaded RGB image array with shape: (444, 787, 3)
